import React, { useState } from 'react';
import { Upload, X, FileText, Download, Sparkles } from 'lucide-react';
import { Proposal } from '../App';

interface EventDocumentationProps {
  proposal: Proposal;
}

export function EventDocumentation({ proposal }: EventDocumentationProps) {
  const [members, setMembers] = useState<string[]>([]);
  const [memberInput, setMemberInput] = useState('');
  const [resources, setResources] = useState('');
  const [attendees, setAttendees] = useState('');
  const [posterFile, setPosterFile] = useState<string>('');
  const [photoFiles, setPhotoFiles] = useState<string[]>([]);
  const [feedbackFile, setFeedbackFile] = useState<string>('');
  const [showReport, setShowReport] = useState(false);

  const handleAddMember = () => {
    if (memberInput.trim()) {
      setMembers([...members, memberInput.trim()]);
      setMemberInput('');
    }
  };

  const handleRemoveMember = (index: number) => {
    setMembers(members.filter((_, i) => i !== index));
  };

  const handlePosterUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) setPosterFile(file.name);
  };

  const handlePhotosUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    setPhotoFiles(files.map(f => f.name));
  };

  const handleFeedbackUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) setFeedbackFile(file.name);
  };

  const handleGenerateReport = () => {
    setShowReport(true);
  };

  const mockReport = `
# Event Report: ${proposal.eventName}

## Event Overview
The ${proposal.eventName} was successfully conducted on ${new Date(proposal.date).toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })}. This event aimed to ${proposal.objective.toLowerCase()}

## Event Details

**Coordinators:** ${proposal.coordinators}

**Objective:** ${proposal.objective}

**Resources & Requirements:** ${proposal.requirements}

## Participation Statistics

- **Total Attendees:** ${attendees || '0'}
- **Team Members Involved:** ${members.length}
- **Resources Utilized:** ${resources || 'Standard equipment'}

## Key Outcomes

The event successfully met its objectives with strong participant engagement. Feedback from attendees was overwhelmingly positive, with participants appreciating the hands-on approach and practical knowledge gained.

${members.length > 0 ? `## Team Members\n\nThe following members contributed to organizing and executing this event:\n${members.map(m => `- ${m}`).join('\n')}` : ''}

## Feedback Highlights

Based on the feedback form responses:
- 92% of participants rated the event as "Excellent" or "Very Good"
- 88% found the content relevant to their academic/career goals
- 95% would recommend similar events to their peers

## Documentation

Event poster and photographs have been archived for future reference and promotional materials.

## Conclusion

The ${proposal.eventName} was a successful initiative that achieved its stated objectives and received positive feedback from participants. The organizing team demonstrated excellent coordination and execution skills.

---
*This report was automatically generated by the ACM Event Manager system.*
  `;

  return (
    <div className="max-w-7xl mx-auto">
      <div className="mb-6">
        <h2 className="text-2xl font-semibold text-gray-900">Event Documentation</h2>
        <p className="text-sm text-gray-600 mt-1">{proposal.eventName}</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Main Documentation Form */}
        <div className="lg:col-span-2 space-y-6">
          {/* Read-only Section */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Proposal Information</h3>
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Event Objective</label>
                <div className="px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm text-gray-700">
                  {proposal.objective}
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Requirements</label>
                <div className="px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm text-gray-700">
                  {proposal.requirements}
                </div>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">Coordinators & Co-Coordinators</label>
                <div className="px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-lg text-sm text-gray-700">
                  {proposal.coordinators}
                </div>
              </div>
            </div>
          </div>

          {/* Editable Section */}
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6">
            <h3 className="font-semibold text-gray-900 mb-4">Event Details</h3>
            <div className="space-y-6">
              {/* Members' Names */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Members' Names</label>
                <div className="flex gap-2 mb-2">
                  <input
                    type="text"
                    value={memberInput}
                    onChange={(e) => setMemberInput(e.target.value)}
                    onKeyPress={(e) => e.key === 'Enter' && (e.preventDefault(), handleAddMember())}
                    className="flex-1 px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-600 focus:border-transparent outline-none transition"
                    placeholder="Enter member name and press Enter"
                  />
                  <button
                    type="button"
                    onClick={handleAddMember}
                    className="px-4 py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition"
                  >
                    Add
                  </button>
                </div>
                <div className="flex flex-wrap gap-2">
                  {members.map((member, index) => (
                    <span
                      key={index}
                      className="inline-flex items-center gap-1 px-3 py-1 bg-blue-100 text-blue-700 rounded-full text-sm"
                    >
                      {member}
                      <button
                        onClick={() => handleRemoveMember(index)}
                        className="hover:bg-blue-200 rounded-full p-0.5"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </span>
                  ))}
                </div>
              </div>

              {/* Resources Used */}
              <div>
                <label htmlFor="resources" className="block text-sm font-medium text-gray-700 mb-2">
                  Resources Used
                </label>
                <textarea
                  id="resources"
                  rows={3}
                  value={resources}
                  onChange={(e) => setResources(e.target.value)}
                  className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-600 focus:border-transparent outline-none transition resize-none"
                  placeholder="List all resources and materials used..."
                />
              </div>

              {/* Number of Attendees */}
              <div>
                <label htmlFor="attendees" className="block text-sm font-medium text-gray-700 mb-2">
                  Number of Attendees
                </label>
                <input
                  type="number"
                  id="attendees"
                  value={attendees}
                  onChange={(e) => setAttendees(e.target.value)}
                  className="w-full px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-600 focus:border-transparent outline-none transition"
                  placeholder="e.g., 45"
                />
              </div>

              {/* Upload Event Poster */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Upload Event Poster</label>
                <input
                  type="file"
                  accept="image/*"
                  onChange={handlePosterUpload}
                  className="hidden"
                  id="posterUpload"
                />
                <label
                  htmlFor="posterUpload"
                  className="flex items-center justify-center gap-2 w-full px-4 py-3 border-2 border-dashed border-gray-300 rounded-lg hover:border-blue-500 hover:bg-blue-50 transition cursor-pointer"
                >
                  {posterFile ? (
                    <>
                      <FileText className="w-5 h-5 text-blue-600" />
                      <span className="text-sm text-gray-700">{posterFile}</span>
                    </>
                  ) : (
                    <>
                      <Upload className="w-5 h-5 text-gray-400" />
                      <span className="text-sm text-gray-600">Click to upload poster</span>
                    </>
                  )}
                </label>
              </div>

              {/* Upload Event Photos */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">Upload Event Photos</label>
                <input
                  type="file"
                  accept="image/*"
                  multiple
                  onChange={handlePhotosUpload}
                  className="hidden"
                  id="photosUpload"
                />
                <label
                  htmlFor="photosUpload"
                  className="flex items-center justify-center gap-2 w-full px-4 py-3 border-2 border-dashed border-gray-300 rounded-lg hover:border-blue-500 hover:bg-blue-50 transition cursor-pointer"
                >
                  <Upload className="w-5 h-5 text-gray-400" />
                  <span className="text-sm text-gray-600">
                    {photoFiles.length > 0 ? `${photoFiles.length} photo(s) selected` : 'Click to upload photos'}
                  </span>
                </label>
              </div>

              {/* Upload Feedback Excel */}
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-2">
                  Upload Google Form Feedback Excel Sheet
                </label>
                <input
                  type="file"
                  accept=".xlsx,.xls,.csv"
                  onChange={handleFeedbackUpload}
                  className="hidden"
                  id="feedbackUpload"
                />
                <label
                  htmlFor="feedbackUpload"
                  className="flex items-center justify-center gap-2 w-full px-4 py-3 border-2 border-dashed border-gray-300 rounded-lg hover:border-blue-500 hover:bg-blue-50 transition cursor-pointer"
                >
                  {feedbackFile ? (
                    <>
                      <FileText className="w-5 h-5 text-blue-600" />
                      <span className="text-sm text-gray-700">{feedbackFile}</span>
                    </>
                  ) : (
                    <>
                      <Upload className="w-5 h-5 text-gray-400" />
                      <span className="text-sm text-gray-600">Click to upload Excel sheet</span>
                    </>
                  )}
                </label>
              </div>

              {/* Generate Report Button */}
              <button
                onClick={handleGenerateReport}
                className="w-full flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white py-3 px-6 rounded-lg transition font-medium shadow-sm"
              >
                <Sparkles className="w-5 h-5" />
                Generate Event Report
              </button>
            </div>
          </div>
        </div>

        {/* AI Report Section */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 sticky top-8">
            <div className="flex items-center gap-2 mb-4">
              <Sparkles className="w-5 h-5 text-blue-600" />
              <h3 className="font-semibold text-gray-900">AI-Generated Event Report</h3>
            </div>

            {showReport ? (
              <>
                <div className="prose prose-sm max-w-none mb-4 max-h-[600px] overflow-y-auto text-sm text-gray-700 whitespace-pre-wrap">
                  {mockReport}
                </div>
                <button className="w-full flex items-center justify-center gap-2 bg-blue-600 hover:bg-blue-700 text-white py-2.5 px-4 rounded-lg transition font-medium">
                  <Download className="w-4 h-4" />
                  Download Report (PDF)
                </button>
              </>
            ) : (
              <div className="text-center py-12">
                <Sparkles className="w-12 h-12 text-gray-300 mx-auto mb-3" />
                <p className="text-sm text-gray-500">
                  Fill in the event details and click "Generate Event Report" to create an AI-powered summary.
                </p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
